PUT {{url}}/api/User
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": "af635ed8-9a96-4ecb-a2bd-2d6e59832eb5",
  "name": "Ilcoglione",
  "surname": "Doe",
  "email": "john.doe@example.com",
  "password": "se232222",
  "dateOfBirth": "2000-01-01"
}