PUT {{url}}/api/User
Content-Type: application/json

{
  "id": "a986b437-0a27-4649-ad0b-abbbe532e09e",
  "name": "Ilcoglione",
  "surname": "Doe",
  "email": "john.doe@example.com",
  "password": "se232222",
  "dateOfBirth": "2000-01-01"
}