POST {{url}}/api/Team
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Pollosacro",
  "description": "Il pollo è sacro qui",
  "managerId": "6ced1c6e-b24f-42c2-933b-19f431931762"
}